export ZFS_PATH=$PWD/zfs-update
export WSL_KERNEL_LOC=$PWD
export repo_url=https://github.com/openzfs/zfs.git
export target_tag=""

#if [ ! -d "$ZFS_PATH" ]; then
#    echo "$ZFS_PATH does not exist."
#    exit
#fi

read -p "Enter zfs tag to update to: " target_tag

if [ "$target_tag" = "" ]; then
    echo "Tag cannot be empty"
    exit 1
fi

if git ls-remote --exit-code --tags "$repo_url" "refs/tags/$target_tag"; then
    #echo "Tag $target_tag exists in the repository."
    git clone --depth 1 -b $target_tag "$repo_url" $ZFS_PATH
else
    echo "Tag $target_tag does not exist in $repo_url."
    exit 1
fi

if [ ! -f "$WSL_KERNEL_LOC/out/.config" ]; then
    cp $WSL_KERNEL_LOC/Microsoft/config-wsl $WSL_KERNEL_LOC/out/.config
fi

make Microsoft/config-wsl \
        O=out \
        -s \
        -j${cpus}

cp out/.config ./
make prepare -s

cd $ZFS_PATH
sh autogen.sh
./configure --prefix=/ --libdir=/lib --includedir=/usr/include --datarootdir=/usr/share --enable-linux-builtin=yes --with-linux=$WSL_KERNEL_LOC --with-linux-obj=$WSL_KERNEL_LOC
./copy-builtin $WSL_KERNEL_LOC

cd $WSL_KERNEL_LOC
make mrproper
make clean

rm -rf $ZFS_PATH

git add include/zfs/ fs/zfs/
git commit -m "fs: zfs: Update to $target_tag

This is an autogenerated commit"

echo done
